### ISSUE TITLE
max tokens in this code.

### ISSUE THREAD

**Issue by jolawre** [peremartra/Large-Language-Model-Notebooks-Course#1]
hey, i have seen this code. thanks for this. but am rising an issue here. since prompts are send to openAI, if user has more than 500 products here will be heated with max token. what to do is to append something like vectordb or anything which will act as a stock search. for example you can append context as

    ```
prompt = inp.value_input
    inp.value = ''
    context.append({'role':'system', 'content':f"""stock list and prices as follow {get_vectordb(prompt)}"""})
    context.append({'role':'user', 'content':f"{prompt}"})
```

**Comment by peremartra** [comment]
Thanks, @jolawre  I was planning to cover vector databases a bit later, in the following notebooks of the course :-)
Thanks for the contribution, I will use it as an example in it for a more advanced notebook.

**Comment by peremartra** [comment]
Added a Note in the Notebook, indicating that is possible to reach the max num of tokens if the Items in the menu is too large :-)
