### ISSUE TITLE
wrong url in 5-Fine Tuning - Fine-Tuning with LoRA using PEFT from Hugging Face

### ISSUE THREAD

**Issue by deepakdeore2004** [peremartra/Large-Language-Model-Notebooks-Course#18]
"[Prompt tuning using PEFT Library from Hugging Face.](https://github.com/peremartra/Large-Language-Model-Notebooks-Course/tree/main/5-Fine%20Tuning#prompt-tuning-using-peft-library-from-hugging-face)" and "[Fine-Tuning with LoRA using PEFT from Hugging Face.](https://github.com/peremartra/Large-Language-Model-Notebooks-Course/tree/main/5-Fine%20Tuning#fine-tuning-with-lora-using-peft-from-hugging-face)" point to same article link

"Fine-Tuning with LoRA using PEFT from Hugging Face" should have correct article link

**Comment by peremartra** [comment]
Solved! Thanks a lot!
