### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by parya-j** [peremartra/Large-Language-Model-Notebooks-Course#19]
Hi,

dataset(s) are not available for:
[**HOW TO USE A VECTOR / EMBEDDING DATABASE TO PROVIDE CONTEXT TO A LARGE LANGUAGE MODEL**](https://github.com/peremartra/Large-Language-Model-Notebooks-Course/blob/main/2-Vector%20Databases%20with%20LLMs/how-to-use-a-embedding-database-with-a-llm-from-hf.ipynb)

**Comment by peremartra** [comment]
Hi parya-j, 

I just go thought the complete Notebook without problems. Check that yopu are woking with version 13 or 14 of the notebook in Kaggle. 

I just uploaded 2_1_Vector_Databases_LLMs.ipynb, that is mainly the same notebook but prepared to be executed in google colab. Try it if you are still having problmes with the notebook on Kaggle. 

Pere.
