### ISSUE TITLE
Could not run the first and the second notebook

### ISSUE THREAD

**Issue by jwlyn** [peremartra/Large-Language-Model-Notebooks-Course#24]
Error message from the First_Chatbot_OpenAI 
---------------------------------------------------------------------------
RateLimitError                            Traceback (most recent call last)
[<ipython-input-59-ab9489c1be57>](https://localhost:8080/#) in <cell line: 49>()
     50     client_prompt,
     51     pn.Row(button_conversation),
---> 52     pn.panel(interactive_conversation, loading_indicator=True),
     53 )
     54 

17 frames
[/usr/local/lib/python3.10/dist-packages/openai/_base_client.py](https://localhost:8080/#) in _request(self, cast_to, options, remaining_retries, stream, stream_cls)
   1039         ...
   1040 
-> 1041     def post(
   1042         self,
   1043         path: str,

RateLimitError: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

----------------------

Error message from the second notebook

<img width="1272" alt="Screenshot 2024-09-03 at 12 23 33" src="https://github.com/user-attachments/assets/5e31b337-40a6-4371-ab63-c0f25887bbde">

**Comment by peremartra** [comment]
Hi!

You are getting an error from Open ai, about your quota.

The easiest way to avoid this kind of limitations with the quota assigned
by Openai is using the prepaid system. Just pre charge a bit amount and you
will be able to avoid it.

Sorry, I got the same problem with OpenAI, and I had no idea why they limit
the credit limit.
