### ISSUE TITLE
OOM in qlora notebook's inference, free tier Colab

### ISSUE THREAD

**Issue by ffreemt** [peremartra/Large-Language-Model-Notebooks-Course#6]
Thanks so much for the nice cource.

I am trying to follow your QLora notebook (QLoRA Tuning using PEFT from Hugging Face https://github.com/peremartra/Large-Language-Model-Notebooks-Course/blob/main/5-Fine%20Tuning/QLoRA_Tuning_PEFT.ipynb) on free tier colab. The training went fine. But the "Load the Model" code in "Inference with the pretrained model" part
```
#Load the Model.
loaded_model = AutoPeftModelForCausalLM.from_pretrained(
                                        peft_model_path,
                                        torch_dtype=torch.bfloat16,
                                        is_trainable=False,
                                        load_in_4bit=True,
                                        device_map = 'auto')
```
always results in an OOM (with error messages "Your session crashed after using all available RAM").

I wonder what the problem can be.

**Comment by ffreemt** [comment]
I tried the notebook in kaggle (which provides 30G RAM). 17+G RAM is required.

**Comment by peremartra** [comment]
Added a note in the notebook :-) Thanks!
